apiVersion: batch/v1
kind: Job
metadata:
  name: redis-helper
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: redis
        name: redis-helper
        command: ["redis-cli"]
        args: ["-h","redis","set","cristian","{{ randAlphaNum 5 }}"]
status: {}

